const products=[
 {name:'Golden Pearl Earrings',category:'Earrings',price:'$48.00',desc:'Luminous freshwater pearls on 18k gold vermeil.',image:'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=700&q=85'},
 {name:'Elegant Stone Necklace',category:'Necklaces',price:'$86.00',desc:'A delicate chain finished with a champagne stone.',image:'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=700&q=85'},
 {name:'Minimal Gold Bracelet',category:'Bracelets',price:'$54.00',desc:'A barely-there everyday essential in polished gold.',image:'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=700&q=85'},
 {name:'Crystal Signet Ring',category:'Rings',price:'$42.00',desc:'A softly sculptural ring with a crystal centre.',image:'https://images.unsplash.com/photo-1603561596112-db7d2e4d6c5e?auto=format&fit=crop&w=700&q=85'},
 {name:'Pearl Jewellery Set',category:'Sets',price:'$112.00',desc:'A timeless necklace and earring pairing for occasions.',image:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=700&q=85'},
 {name:'Sculptural Gold Hoops',category:'Earrings',price:'$39.00',desc:'Polished curves made for a little daily drama.',image:'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=700&q=85'},
 {name:'Fine Chain Layer',category:'Necklaces',price:'$68.00',desc:'The perfect foundation for your personal stack.',image:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=85'},
 {name:'Fashion Bangles',category:'Bracelets',price:'$45.00',desc:'A softly hammered trio with a warm golden finish.',image:'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=700&q=85'}
];
const grid=document.querySelector('#productGrid');let cart=0;
function render(filter='All'){grid.innerHTML=products.filter(p=>filter==='All'||p.category===filter).map((p,i)=>`<article class="product-card"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${p.name}"><button class="wishlist" aria-label="Add ${p.name} to wishlist">♡</button></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-footer"><span class="price">${p.price}</span><div class="card-actions"><button class="add-btn" data-name="${p.name}">Add to cart</button><button class="buy-btn" data-name="${p.name}">Buy now</button></div></div></div></article>`).join('');attachCardEvents()}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function attachCardEvents(){document.querySelectorAll('.wishlist').forEach(b=>b.onclick=()=>{b.classList.toggle('loved');b.textContent=b.classList.contains('loved')?'♥':'♡';toast(b.classList.contains('loved')?'Added to your wishlist':'Removed from your wishlist')});document.querySelectorAll('.add-btn').forEach(b=>b.onclick=()=>{cart++;document.querySelector('.bag-count').textContent=cart;toast(`${b.dataset.name} added to your bag`)});document.querySelectorAll('.buy-btn').forEach(b=>b.onclick=()=>{cart++;document.querySelector('.bag-count').textContent=cart;toast('Your item is ready for checkout')})}
document.querySelectorAll('.filter-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
document.querySelectorAll('.category-card').forEach(card=>card.onclick=()=>{const filter=card.dataset.filter;document.querySelectorAll('.filter-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render(filter)});
document.querySelector('.menu-toggle').onclick=()=>document.querySelector('.mobile-nav').classList.toggle('open');document.querySelector('.search-toggle').onclick=()=>{const p=document.querySelector('.search-panel');p.classList.toggle('open');if(p.classList.contains('open'))document.querySelector('#searchInput').focus()};document.querySelector('#searchInput').onkeydown=e=>{if(e.key==='Enter'){const term=e.target.value.toLowerCase();const match=products.find(p=>p.name.toLowerCase().includes(term)||p.category.toLowerCase().includes(term));if(match){render(match.category);document.querySelector('#shop').scrollIntoView();toast(`Showing ${match.category.toLowerCase()}`)}else toast('No pieces found — try another search')}};document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();toast('Thank you — welcome to the J&A list');e.target.reset()};document.querySelector('.bag-btn').onclick=()=>toast(cart?`${cart} item${cart===1?'':'s'} in your bag`:'Your bag is waiting for something beautiful');render();
